### ISSUE TITLE
npm run build fails (cannot find scoped css)

### ISSUE THREAD

**Issue by andrewwilkin** [McNerdius/TailBlazor-Templates#20]
Trying to follow along with the steps, and probably got something wrong along the way.

Running "npm run build" throws the following error:

```
> client@1.0.0 build
> npx tailwindcss --config tailwind.config.js --postcss postcss.config.js -i site.css -o ./wwwroot/site.min.css

C:\Users\User\source\repos\CarpeDatumPortal\CarpeDatumPortal\Client\node_modules\postcss-import\lib\resolve-id.js:35
      throw new Error(
            ^

Error: Failed to find './obj/scopedcss/bundle/site.styles.css'
  in [
    C:\Users\User\source\repos\CarpeDatumPortal\CarpeDatumPortal\Client
  ]
    at C:\Users\User\source\repos\CarpeDatumPortal\CarpeDatumPortal\Client\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async LazyResult.runAsync (C:\Users\User\source\repos\CarpeDatumPortal\CarpeDatumPortal\Client\node_modules\tailwindcss\peers\index.js:5153:15)

Node.js v17.3.0
```

Pointers appreciated :)

**Comment by andrewwilkin** [comment]
Hah, seen the error in my ways not updated the site.css import line to reflect my project.
